# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5b95da41537fae7a044ce073bb0f7c9aa22d0735914c9715c6c51a92dbb47bdc1d1db96a4a98bbaff307ff81a84eb233211cde21c9806441bb83146bec03ca0

test:
  secret_key_base: 12e9f28697aaaa340288da08dbcaa77109647530c223d60f3a650a71c31f4c75c2ed919e04bd4909f2e43488bfcfedb741f66cd5e6479ff713c801ef554d0bed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
