source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use postgresql as the database for Active Record
gem 'pg'
# Use CoffeeScript for .coffee assets and views

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

#from DockYard tutorial http://reefpoints.dockyard.com/2014/05/07/building-an-ember-app-with-rails-part-1.html
### 0.9.3 is specified because 0.10.0RC is coming out and is not backwards compatible
#https://github.com/rails-api/active_model_serializers
gem 'active_model_serializers', '0.9.3'


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

