source 'https://rubygems.org'

ruby '2.3.0'

gem 'rails', '> 4'
# Use postgresql as the database for Active Record
gem 'pg'

gem 'sdoc', '~> 0.4.0', group: :doc

gem 'active_model_serializers', '0.9.3'
gem 'sass-rails'
gem 'uglifier'
# gem 'coffee-rails'
gem 'jquery-rails'
gem 'jbuilder'
gem 'rails_12factor', group: :production
gem 'puma'

gem 'bower-rails'


group :development, :test do
  gem 'rspec-rails'
  gem 'poltergeist'
end

